#!/usr/bin/php -q
<?php

if (file_exists('vendor/autoload.php')) {
    require_once 'vendor/autoload.php';

    if (file_exists('application/command/bootstrap.php')) {
	    require_once 'application/command/bootstrap.php';
	} else {
	    echo 'Missing ciscript cmd';
	}
} else {
    echo 'Composer package not found, run composer install and try again';
}
